### ISSUE TITLE
binary files

### ISSUE THREAD

**Issue by lenerd** [Saremox/MessingWithSlick#1]
Ist es notwendig, die shared objects im Repository zu haben? Kann man die nicht als dependency angeben?

**Comment by Saremox** [comment]
Ich kenne leider keinen weg fuer Java .jars und jni .so`s als dependency anzugegen sodass diese automatisch aufgeloesst werden koennen. Waere vllt ein projekt wert ein solches tool zu schreiben.

**Comment by Saremox** [comment]
Apache Maven scheint das wohl machen zu koennen. Werde mir das mal angucken ;)

**Comment by lenerd** [comment]
Ich weiß nicht viel von Java Buildsystemen, wie sieht das mit den Shared Objects/DLLs aus? Eigentlich hat man die Libs doch einmal im System und linkt sie dynamisch für alle Programme.

**Comment by Saremox** [comment]
joa sind leider keine typischen libs die man mal eben installieren kann. Mojang hat seinen eigenen Launcher gebaut der die libs nachlaedt fuer Minecraft. Ist halt nicht ganz so schoen und automatisch als wenn man Python/C/C++ schreibt

**Comment by lenerd** [comment]
OpenAL zumindest bekommt man über Paketmanagement. Bei C/C++ oder Python wird in bestimten Pfaden nach SOs bzw. Python Modulen gesucht.
Du könntest aber auch die Libs vom Buildscript/Packagescript bei Bedarf herunterladen lassen, was vermutlich die einfachste Lösung sein sollte.
